//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteKnownTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteKnownTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  This service is deprecated and will go away at some point. For new development use the ExecuteTrajectory action.
        //  Effective since: Indigo 0.7.4, Jade and Kinetic 0.8.3
        //  The trajectory to execute 
        public RobotTrajectoryMsg trajectory;
        //  Set this to true if the service should block until the execution is complete
        public bool wait_for_execution;

        public ExecuteKnownTrajectoryRequest()
        {
            this.trajectory = new RobotTrajectoryMsg();
            this.wait_for_execution = false;
        }

        public ExecuteKnownTrajectoryRequest(RobotTrajectoryMsg trajectory, bool wait_for_execution)
        {
            this.trajectory = trajectory;
            this.wait_for_execution = wait_for_execution;
        }

        public static ExecuteKnownTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new ExecuteKnownTrajectoryRequest(deserializer);

        private ExecuteKnownTrajectoryRequest(MessageDeserializer deserializer)
        {
            this.trajectory = RobotTrajectoryMsg.Deserialize(deserializer);
            deserializer.Read(out this.wait_for_execution);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
            serializer.Write(this.wait_for_execution);
        }

        public override string ToString()
        {
            return "ExecuteKnownTrajectoryRequest: " +
            "\ntrajectory: " + trajectory.ToString() +
            "\nwait_for_execution: " + wait_for_execution.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
