//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetMotionPlanRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetMotionPlan";
        public override string RosMessageName => k_RosMessageName;

        //  This service contains the definition for a request to the motion
        //  planner and the output it provides
        public MotionPlanRequestMsg motion_plan_request;

        public GetMotionPlanRequest()
        {
            this.motion_plan_request = new MotionPlanRequestMsg();
        }

        public GetMotionPlanRequest(MotionPlanRequestMsg motion_plan_request)
        {
            this.motion_plan_request = motion_plan_request;
        }

        public static GetMotionPlanRequest Deserialize(MessageDeserializer deserializer) => new GetMotionPlanRequest(deserializer);

        private GetMotionPlanRequest(MessageDeserializer deserializer)
        {
            this.motion_plan_request = MotionPlanRequestMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motion_plan_request);
        }

        public override string ToString()
        {
            return "GetMotionPlanRequest: " +
            "\nmotion_plan_request: " + motion_plan_request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
