//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetStateValidityRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetStateValidity";
        public override string RosMessageName => k_RosMessageName;

        public RobotStateMsg robot_state;
        public string group_name;
        public ConstraintsMsg constraints;

        public GetStateValidityRequest()
        {
            this.robot_state = new RobotStateMsg();
            this.group_name = "";
            this.constraints = new ConstraintsMsg();
        }

        public GetStateValidityRequest(RobotStateMsg robot_state, string group_name, ConstraintsMsg constraints)
        {
            this.robot_state = robot_state;
            this.group_name = group_name;
            this.constraints = constraints;
        }

        public static GetStateValidityRequest Deserialize(MessageDeserializer deserializer) => new GetStateValidityRequest(deserializer);

        private GetStateValidityRequest(MessageDeserializer deserializer)
        {
            this.robot_state = RobotStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.group_name);
            this.constraints = ConstraintsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_state);
            serializer.Write(this.group_name);
            serializer.Write(this.constraints);
        }

        public override string ToString()
        {
            return "GetStateValidityRequest: " +
            "\nrobot_state: " + robot_state.ToString() +
            "\ngroup_name: " + group_name.ToString() +
            "\nconstraints: " + constraints.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
