//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetStateValidityResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetStateValidity";
        public override string RosMessageName => k_RosMessageName;

        public bool valid;
        public ContactInformationMsg[] contacts;
        public CostSourceMsg[] cost_sources;
        public ConstraintEvalResultMsg[] constraint_result;

        public GetStateValidityResponse()
        {
            this.valid = false;
            this.contacts = new ContactInformationMsg[0];
            this.cost_sources = new CostSourceMsg[0];
            this.constraint_result = new ConstraintEvalResultMsg[0];
        }

        public GetStateValidityResponse(bool valid, ContactInformationMsg[] contacts, CostSourceMsg[] cost_sources, ConstraintEvalResultMsg[] constraint_result)
        {
            this.valid = valid;
            this.contacts = contacts;
            this.cost_sources = cost_sources;
            this.constraint_result = constraint_result;
        }

        public static GetStateValidityResponse Deserialize(MessageDeserializer deserializer) => new GetStateValidityResponse(deserializer);

        private GetStateValidityResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.valid);
            deserializer.Read(out this.contacts, ContactInformationMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.cost_sources, CostSourceMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.constraint_result, ConstraintEvalResultMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.valid);
            serializer.WriteLength(this.contacts);
            serializer.Write(this.contacts);
            serializer.WriteLength(this.cost_sources);
            serializer.Write(this.cost_sources);
            serializer.WriteLength(this.constraint_result);
            serializer.Write(this.constraint_result);
        }

        public override string ToString()
        {
            return "GetStateValidityResponse: " +
            "\nvalid: " + valid.ToString() +
            "\ncontacts: " + System.String.Join(", ", contacts.ToList()) +
            "\ncost_sources: " + System.String.Join(", ", cost_sources.ToList()) +
            "\nconstraint_result: " + System.String.Join(", ", constraint_result.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
