//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ListRobotStatesInWarehouseRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ListRobotStatesInWarehouse";
        public override string RosMessageName => k_RosMessageName;

        public string regex;
        public string robot;

        public ListRobotStatesInWarehouseRequest()
        {
            this.regex = "";
            this.robot = "";
        }

        public ListRobotStatesInWarehouseRequest(string regex, string robot)
        {
            this.regex = regex;
            this.robot = robot;
        }

        public static ListRobotStatesInWarehouseRequest Deserialize(MessageDeserializer deserializer) => new ListRobotStatesInWarehouseRequest(deserializer);

        private ListRobotStatesInWarehouseRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.regex);
            deserializer.Read(out this.robot);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.regex);
            serializer.Write(this.robot);
        }

        public override string ToString()
        {
            return "ListRobotStatesInWarehouseRequest: " +
            "\nregex: " + regex.ToString() +
            "\nrobot: " + robot.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
