//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class LoadMapRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/LoadMap";
        public override string RosMessageName => k_RosMessageName;

        public string filename;

        public LoadMapRequest()
        {
            this.filename = "";
        }

        public LoadMapRequest(string filename)
        {
            this.filename = filename;
        }

        public static LoadMapRequest Deserialize(MessageDeserializer deserializer) => new LoadMapRequest(deserializer);

        private LoadMapRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filename);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filename);
        }

        public override string ToString()
        {
            return "LoadMapRequest: " +
            "\nfilename: " + filename.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
