//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class QueryPlannerInterfacesRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/QueryPlannerInterfaces";
        public override string RosMessageName => k_RosMessageName;


        public QueryPlannerInterfacesRequest()
        {
        }
        public static QueryPlannerInterfacesRequest Deserialize(MessageDeserializer deserializer) => new QueryPlannerInterfacesRequest(deserializer);

        private QueryPlannerInterfacesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "QueryPlannerInterfacesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
