//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class SetPlannerParamsResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/SetPlannerParams";
        public override string RosMessageName => k_RosMessageName;


        public SetPlannerParamsResponse()
        {
        }
        public static SetPlannerParamsResponse Deserialize(MessageDeserializer deserializer) => new SetPlannerParamsResponse(deserializer);

        private SetPlannerParamsResponse(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SetPlannerParamsResponse: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
