//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class CheckIfRobotStateExistsInWarehouseResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/CheckIfRobotStateExistsInWarehouse";
        public override string RosMessageName => k_RosMessageName;

        public bool exists;

        public CheckIfRobotStateExistsInWarehouseResponse()
        {
            this.exists = false;
        }

        public CheckIfRobotStateExistsInWarehouseResponse(bool exists)
        {
            this.exists = exists;
        }

        public static CheckIfRobotStateExistsInWarehouseResponse Deserialize(MessageDeserializer deserializer) => new CheckIfRobotStateExistsInWarehouseResponse(deserializer);

        private CheckIfRobotStateExistsInWarehouseResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exists);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exists);
        }

        public override string ToString()
        {
            return "CheckIfRobotStateExistsInWarehouseResponse: " +
            "\nexists: " + exists.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
