//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteKnownTrajectoryResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteKnownTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodesMsg error_code;

        public ExecuteKnownTrajectoryResponse()
        {
            this.error_code = new MoveItErrorCodesMsg();
        }

        public ExecuteKnownTrajectoryResponse(MoveItErrorCodesMsg error_code)
        {
            this.error_code = error_code;
        }

        public static ExecuteKnownTrajectoryResponse Deserialize(MessageDeserializer deserializer) => new ExecuteKnownTrajectoryResponse(deserializer);

        private ExecuteKnownTrajectoryResponse(MessageDeserializer deserializer)
        {
            this.error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "ExecuteKnownTrajectoryResponse: " +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
