//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetMotionSequenceResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetMotionSequence";
        public override string RosMessageName => k_RosMessageName;

        //  Response to the planning request
        public MotionSequenceResponseMsg response;

        public GetMotionSequenceResponse()
        {
            this.response = new MotionSequenceResponseMsg();
        }

        public GetMotionSequenceResponse(MotionSequenceResponseMsg response)
        {
            this.response = response;
        }

        public static GetMotionSequenceResponse Deserialize(MessageDeserializer deserializer) => new GetMotionSequenceResponse(deserializer);

        private GetMotionSequenceResponse(MessageDeserializer deserializer)
        {
            this.response = MotionSequenceResponseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "GetMotionSequenceResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
