//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetPlannerParamsResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetPlannerParams";
        public override string RosMessageName => k_RosMessageName;

        //  parameters as key-value pairs
        public PlannerParamsMsg @params;

        public GetPlannerParamsResponse()
        {
            this.@params = new PlannerParamsMsg();
        }

        public GetPlannerParamsResponse(PlannerParamsMsg @params)
        {
            this.@params = @params;
        }

        public static GetPlannerParamsResponse Deserialize(MessageDeserializer deserializer) => new GetPlannerParamsResponse(deserializer);

        private GetPlannerParamsResponse(MessageDeserializer deserializer)
        {
            this.@params = PlannerParamsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@params);
        }

        public override string ToString()
        {
            return "GetPlannerParamsResponse: " +
            "\n@params: " + @params.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
