//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetPositionFKRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetPositionFK";
        public override string RosMessageName => k_RosMessageName;

        //  A service definition for a standard forward kinematics service
        //  The frame_id in the header message is the frame in which 
        //  the forward kinematics poses will be returned
        public HeaderMsg header;
        //  A vector of link name for which forward kinematics must be computed
        public string[] fk_link_names;
        //  A robot state consisting of joint names and joint positions to be used for forward kinematics
        public RobotStateMsg robot_state;

        public GetPositionFKRequest()
        {
            this.header = new HeaderMsg();
            this.fk_link_names = new string[0];
            this.robot_state = new RobotStateMsg();
        }

        public GetPositionFKRequest(HeaderMsg header, string[] fk_link_names, RobotStateMsg robot_state)
        {
            this.header = header;
            this.fk_link_names = fk_link_names;
            this.robot_state = robot_state;
        }

        public static GetPositionFKRequest Deserialize(MessageDeserializer deserializer) => new GetPositionFKRequest(deserializer);

        private GetPositionFKRequest(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.fk_link_names, deserializer.ReadLength());
            this.robot_state = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.fk_link_names);
            serializer.Write(this.fk_link_names);
            serializer.Write(this.robot_state);
        }

        public override string ToString()
        {
            return "GetPositionFKRequest: " +
            "\nheader: " + header.ToString() +
            "\nfk_link_names: " + System.String.Join(", ", fk_link_names.ToList()) +
            "\nrobot_state: " + robot_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
