//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class SaveRobotStateToWarehouseRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/SaveRobotStateToWarehouse";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string robot;
        public RobotStateMsg state;

        public SaveRobotStateToWarehouseRequest()
        {
            this.name = "";
            this.robot = "";
            this.state = new RobotStateMsg();
        }

        public SaveRobotStateToWarehouseRequest(string name, string robot, RobotStateMsg state)
        {
            this.name = name;
            this.robot = robot;
            this.state = state;
        }

        public static SaveRobotStateToWarehouseRequest Deserialize(MessageDeserializer deserializer) => new SaveRobotStateToWarehouseRequest(deserializer);

        private SaveRobotStateToWarehouseRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.robot);
            this.state = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.robot);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "SaveRobotStateToWarehouseRequest: " +
            "\nname: " + name.ToString() +
            "\nrobot: " + robot.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
