//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class DisplayRobotStateMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/DisplayRobotState";
        public override string RosMessageName => k_RosMessageName;

        //  The robot state to display
        public RobotStateMsg state;
        //  Optionally, various links can be highlighted
        public ObjectColorMsg[] highlight_links;

        public DisplayRobotStateMsg()
        {
            this.state = new RobotStateMsg();
            this.highlight_links = new ObjectColorMsg[0];
        }

        public DisplayRobotStateMsg(RobotStateMsg state, ObjectColorMsg[] highlight_links)
        {
            this.state = state;
            this.highlight_links = highlight_links;
        }

        public static DisplayRobotStateMsg Deserialize(MessageDeserializer deserializer) => new DisplayRobotStateMsg(deserializer);

        private DisplayRobotStateMsg(MessageDeserializer deserializer)
        {
            this.state = RobotStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.highlight_links, ObjectColorMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.WriteLength(this.highlight_links);
            serializer.Write(this.highlight_links);
        }

        public override string ToString()
        {
            return "DisplayRobotStateMsg: " +
            "\nstate: " + state.ToString() +
            "\nhighlight_links: " + System.String.Join(", ", highlight_links.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
