//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.JskRecognition
{
    [Serializable]
    public class BoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "jsk_recognition_msgs/BoundingBox";
        public override string RosMessageName => k_RosMessageName;

        //  BoundingBox represents a oriented bounding box.
        public HeaderMsg header;
        public Geometry.PoseMsg pose;
        public Geometry.Vector3Msg dimensions;
        //  size of bounding box (x, y, z)
        //  You can use this field to hold value such as likelihood
        public float value;
        public uint label;

        public BoundingBoxMsg()
        {
            this.header = new HeaderMsg();
            this.pose = new Geometry.PoseMsg();
            this.dimensions = new Geometry.Vector3Msg();
            this.value = 0.0f;
            this.label = 0;
        }

        public BoundingBoxMsg(HeaderMsg header, Geometry.PoseMsg pose, Geometry.Vector3Msg dimensions, float value, uint label)
        {
            this.header = header;
            this.pose = pose;
            this.dimensions = dimensions;
            this.value = value;
            this.label = label;
        }

        public static BoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxMsg(deserializer);

        private BoundingBoxMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.dimensions = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.value);
            deserializer.Read(out this.label);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
            serializer.Write(this.dimensions);
            serializer.Write(this.value);
            serializer.Write(this.label);
        }

        public override string ToString()
        {
            return "BoundingBoxMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString() +
            "\ndimensions: " + dimensions.ToString() +
            "\nvalue: " + value.ToString() +
            "\nlabel: " + label.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
