//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchVr
{
    [Serializable]
    public class ExampleServiceResponse : Message
    {
        public const string k_RosMessageName = "fetch_vr/ExampleService";
        public override string RosMessageName => k_RosMessageName;

        public long sum;

        public ExampleServiceResponse()
        {
            this.sum = 0;
        }

        public ExampleServiceResponse(long sum)
        {
            this.sum = sum;
        }

        public static ExampleServiceResponse Deserialize(MessageDeserializer deserializer) => new ExampleServiceResponse(deserializer);

        private ExampleServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sum);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sum);
        }

        public override string ToString()
        {
            return "ExampleServiceResponse: " +
            "\nsum: " + sum.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
