//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchVr
{
    [Serializable]
    public class ExampleServiceRequest : Message
    {
        public const string k_RosMessageName = "fetch_vr/ExampleService";
        public override string RosMessageName => k_RosMessageName;

        public long x;
        public long y;

        public ExampleServiceRequest()
        {
            this.x = 0;
            this.y = 0;
        }

        public ExampleServiceRequest(long x, long y)
        {
            this.x = x;
            this.y = y;
        }

        public static ExampleServiceRequest Deserialize(MessageDeserializer deserializer) => new ExampleServiceRequest(deserializer);

        private ExampleServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
        }

        public override string ToString()
        {
            return "ExampleServiceRequest: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
