//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchDriver
{
    [Serializable]
    public class DisableChargingResult : Message
    {
        public const string k_RosMessageName = "fetch_driver_msgs/DisableCharging";
        public override string RosMessageName => k_RosMessageName;

        //  Returns true if charging was successfully disabled,
        //  false if we are unable to disable charging
        public bool charging_disabled;

        public DisableChargingResult()
        {
            this.charging_disabled = false;
        }

        public DisableChargingResult(bool charging_disabled)
        {
            this.charging_disabled = charging_disabled;
        }

        public static DisableChargingResult Deserialize(MessageDeserializer deserializer) => new DisableChargingResult(deserializer);

        private DisableChargingResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.charging_disabled);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.charging_disabled);
        }

        public override string ToString()
        {
            return "DisableChargingResult: " +
            "\ncharging_disabled: " + charging_disabled.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
