//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.FetchDriver
{
    [Serializable]
    public class DisableChargingGoal : Message
    {
        public const string k_RosMessageName = "fetch_driver_msgs/DisableCharging";
        public override string RosMessageName => k_RosMessageName;

        //  Disable charging for a specific amount of time
        public DurationMsg disable_duration;

        public DisableChargingGoal()
        {
            this.disable_duration = new DurationMsg();
        }

        public DisableChargingGoal(DurationMsg disable_duration)
        {
            this.disable_duration = disable_duration;
        }

        public static DisableChargingGoal Deserialize(MessageDeserializer deserializer) => new DisableChargingGoal(deserializer);

        private DisableChargingGoal(MessageDeserializer deserializer)
        {
            this.disable_duration = DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.disable_duration);
        }

        public override string ToString()
        {
            return "DisableChargingGoal: " +
            "\ndisable_duration: " + disable_duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
