//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchDriver
{
    [Serializable]
    public class DisableChargingFeedback : Message
    {
        public const string k_RosMessageName = "fetch_driver_msgs/DisableCharging";
        public override string RosMessageName => k_RosMessageName;

        //  No feedback

        public DisableChargingFeedback()
        {
        }
        public static DisableChargingFeedback Deserialize(MessageDeserializer deserializer) => new DisableChargingFeedback(deserializer);

        private DisableChargingFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "DisableChargingFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
