//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchAutoDock
{
    [Serializable]
    public class DockResult : Message
    {
        public const string k_RosMessageName = "fetch_auto_dock_msgs/Dock";
        public override string RosMessageName => k_RosMessageName;

        //  Are we docked and charging?
        public bool docked;
        //  Name of the dock, if known
        public string dock_id;

        public DockResult()
        {
            this.docked = false;
            this.dock_id = "";
        }

        public DockResult(bool docked, string dock_id)
        {
            this.docked = docked;
            this.dock_id = dock_id;
        }

        public static DockResult Deserialize(MessageDeserializer deserializer) => new DockResult(deserializer);

        private DockResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.docked);
            deserializer.Read(out this.dock_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.docked);
            serializer.Write(this.dock_id);
        }

        public override string ToString()
        {
            return "DockResult: " +
            "\ndocked: " + docked.ToString() +
            "\ndock_id: " + dock_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
