//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchAutoDock
{
    [Serializable]
    public class UndockResult : Message
    {
        public const string k_RosMessageName = "fetch_auto_dock_msgs/Undock";
        public override string RosMessageName => k_RosMessageName;

        //  Have we undocked?
        public bool undocked;

        public UndockResult()
        {
            this.undocked = false;
        }

        public UndockResult(bool undocked)
        {
            this.undocked = undocked;
        }

        public static UndockResult Deserialize(MessageDeserializer deserializer) => new UndockResult(deserializer);

        private UndockResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.undocked);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.undocked);
        }

        public override string ToString()
        {
            return "UndockResult: " +
            "\nundocked: " + undocked.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
