//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchAutoDock
{
    [Serializable]
    public class UndockGoal : Message
    {
        public const string k_RosMessageName = "fetch_auto_dock_msgs/Undock";
        public override string RosMessageName => k_RosMessageName;

        //  This action will always pull backwards off the dock
        //  Optionally, we can also turn around 180 degrees
        public bool rotate_in_place;

        public UndockGoal()
        {
            this.rotate_in_place = false;
        }

        public UndockGoal(bool rotate_in_place)
        {
            this.rotate_in_place = rotate_in_place;
        }

        public static UndockGoal Deserialize(MessageDeserializer deserializer) => new UndockGoal(deserializer);

        private UndockGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rotate_in_place);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rotate_in_place);
        }

        public override string ToString()
        {
            return "UndockGoal: " +
            "\nrotate_in_place: " + rotate_in_place.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
