//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.FetchDriver
{
    [Serializable]
    public class GripperStateMsg : Message
    {
        public const string k_RosMessageName = "fetch_driver_msgs/GripperState";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Primary message for a gripper
        // 
        public HeaderMsg header;
        public bool ready;
        public bool faulted;
        public BoardStateMsg[] boards;
        public MotorStateMsg[] motors;
        public JointStateMsg[] joints;

        public GripperStateMsg()
        {
            this.header = new HeaderMsg();
            this.ready = false;
            this.faulted = false;
            this.boards = new BoardStateMsg[0];
            this.motors = new MotorStateMsg[0];
            this.joints = new JointStateMsg[0];
        }

        public GripperStateMsg(HeaderMsg header, bool ready, bool faulted, BoardStateMsg[] boards, MotorStateMsg[] motors, JointStateMsg[] joints)
        {
            this.header = header;
            this.ready = ready;
            this.faulted = faulted;
            this.boards = boards;
            this.motors = motors;
            this.joints = joints;
        }

        public static GripperStateMsg Deserialize(MessageDeserializer deserializer) => new GripperStateMsg(deserializer);

        private GripperStateMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.ready);
            deserializer.Read(out this.faulted);
            deserializer.Read(out this.boards, BoardStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.motors, MotorStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.joints, JointStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.ready);
            serializer.Write(this.faulted);
            serializer.WriteLength(this.boards);
            serializer.Write(this.boards);
            serializer.WriteLength(this.motors);
            serializer.Write(this.motors);
            serializer.WriteLength(this.joints);
            serializer.Write(this.joints);
        }

        public override string ToString()
        {
            return "GripperStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nready: " + ready.ToString() +
            "\nfaulted: " + faulted.ToString() +
            "\nboards: " + System.String.Join(", ", boards.ToList()) +
            "\nmotors: " + System.String.Join(", ", motors.ToList()) +
            "\njoints: " + System.String.Join(", ", joints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
