//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchDriver
{
    [Serializable]
    public class JointStateMsg : Message
    {
        public const string k_RosMessageName = "fetch_driver_msgs/JointState";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public byte control_mode;
        public float desired_position;
        public float desired_velocity;
        public float desired_effort;
        public float position;
        public float velocity;
        public float effort;

        public JointStateMsg()
        {
            this.name = "";
            this.control_mode = 0;
            this.desired_position = 0.0f;
            this.desired_velocity = 0.0f;
            this.desired_effort = 0.0f;
            this.position = 0.0f;
            this.velocity = 0.0f;
            this.effort = 0.0f;
        }

        public JointStateMsg(string name, byte control_mode, float desired_position, float desired_velocity, float desired_effort, float position, float velocity, float effort)
        {
            this.name = name;
            this.control_mode = control_mode;
            this.desired_position = desired_position;
            this.desired_velocity = desired_velocity;
            this.desired_effort = desired_effort;
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
        }

        public static JointStateMsg Deserialize(MessageDeserializer deserializer) => new JointStateMsg(deserializer);

        private JointStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.control_mode);
            deserializer.Read(out this.desired_position);
            deserializer.Read(out this.desired_velocity);
            deserializer.Read(out this.desired_effort);
            deserializer.Read(out this.position);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.effort);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.control_mode);
            serializer.Write(this.desired_position);
            serializer.Write(this.desired_velocity);
            serializer.Write(this.desired_effort);
            serializer.Write(this.position);
            serializer.Write(this.velocity);
            serializer.Write(this.effort);
        }

        public override string ToString()
        {
            return "JointStateMsg: " +
            "\nname: " + name.ToString() +
            "\ncontrol_mode: " + control_mode.ToString() +
            "\ndesired_position: " + desired_position.ToString() +
            "\ndesired_velocity: " + desired_velocity.ToString() +
            "\ndesired_effort: " + desired_effort.ToString() +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\neffort: " + effort.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
