//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.JskRecognition
{
    [Serializable]
    public class BoundingBoxArrayMsg : Message
    {
        public const string k_RosMessageName = "jsk_recognition_msgs/BoundingBoxArray";
        public override string RosMessageName => k_RosMessageName;

        //  BoundingBoxArray is a list of BoundingBox.
        //  You can use jsk_rviz_plugins to visualize BoungingBoxArray on rviz.
        public HeaderMsg header;
        public BoundingBoxMsg[] boxes;

        public BoundingBoxArrayMsg()
        {
            this.header = new HeaderMsg();
            this.boxes = new BoundingBoxMsg[0];
        }

        public BoundingBoxArrayMsg(HeaderMsg header, BoundingBoxMsg[] boxes)
        {
            this.header = header;
            this.boxes = boxes;
        }

        public static BoundingBoxArrayMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxArrayMsg(deserializer);

        private BoundingBoxArrayMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.boxes, BoundingBoxMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.boxes);
            serializer.Write(this.boxes);
        }

        public override string ToString()
        {
            return "BoundingBoxArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nboxes: " + System.String.Join(", ", boxes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
