//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Aruco
{
    [Serializable]
    public class MarkerMsg : Message
    {
        public const string k_RosMessageName = "aruco_msgs/Marker";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public uint id;
        public Geometry.PoseWithCovarianceMsg pose;
        public double confidence;

        public MarkerMsg()
        {
            this.header = new HeaderMsg();
            this.id = 0;
            this.pose = new Geometry.PoseWithCovarianceMsg();
            this.confidence = 0.0;
        }

        public MarkerMsg(HeaderMsg header, uint id, Geometry.PoseWithCovarianceMsg pose, double confidence)
        {
            this.header = header;
            this.id = id;
            this.pose = pose;
            this.confidence = confidence;
        }

        public static MarkerMsg Deserialize(MessageDeserializer deserializer) => new MarkerMsg(deserializer);

        private MarkerMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
            this.pose = Geometry.PoseWithCovarianceMsg.Deserialize(deserializer);
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.id);
            serializer.Write(this.pose);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "MarkerMsg: " +
            "\nheader: " + header.ToString() +
            "\nid: " + id.ToString() +
            "\npose: " + pose.ToString() +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
