//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryGoal : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  The trajectory to execute
        public RobotTrajectoryMsg trajectory;

        public ExecuteTrajectoryGoal()
        {
            this.trajectory = new RobotTrajectoryMsg();
        }

        public ExecuteTrajectoryGoal(RobotTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static ExecuteTrajectoryGoal Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryGoal(deserializer);

        private ExecuteTrajectoryGoal(MessageDeserializer deserializer)
        {
            this.trajectory = RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryGoal: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
