//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryFeedback : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  The internal state that the move group action currently is in
        public string state;

        public ExecuteTrajectoryFeedback()
        {
            this.state = "";
        }

        public ExecuteTrajectoryFeedback(string state)
        {
            this.state = state;
        }

        public static ExecuteTrajectoryFeedback Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryFeedback(deserializer);

        private ExecuteTrajectoryFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryFeedback: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
