//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupSequenceResult : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupSequence";
        public override string RosMessageName => k_RosMessageName;

        //  Response comprising information on all sections of the sequence
        public MotionSequenceResponseMsg response;

        public MoveGroupSequenceResult()
        {
            this.response = new MotionSequenceResponseMsg();
        }

        public MoveGroupSequenceResult(MotionSequenceResponseMsg response)
        {
            this.response = response;
        }

        public static MoveGroupSequenceResult Deserialize(MessageDeserializer deserializer) => new MoveGroupSequenceResult(deserializer);

        private MoveGroupSequenceResult(MessageDeserializer deserializer)
        {
            this.response = MotionSequenceResponseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "MoveGroupSequenceResult: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
