//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupSequenceGoal : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupSequence";
        public override string RosMessageName => k_RosMessageName;

        //  A list of motion commands - one for each section of the sequence
        public MotionSequenceRequestMsg request;
        //  Planning options
        public PlanningOptionsMsg planning_options;

        public MoveGroupSequenceGoal()
        {
            this.request = new MotionSequenceRequestMsg();
            this.planning_options = new PlanningOptionsMsg();
        }

        public MoveGroupSequenceGoal(MotionSequenceRequestMsg request, PlanningOptionsMsg planning_options)
        {
            this.request = request;
            this.planning_options = planning_options;
        }

        public static MoveGroupSequenceGoal Deserialize(MessageDeserializer deserializer) => new MoveGroupSequenceGoal(deserializer);

        private MoveGroupSequenceGoal(MessageDeserializer deserializer)
        {
            this.request = MotionSequenceRequestMsg.Deserialize(deserializer);
            this.planning_options = PlanningOptionsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
            serializer.Write(this.planning_options);
        }

        public override string ToString()
        {
            return "MoveGroupSequenceGoal: " +
            "\nrequest: " + request.ToString() +
            "\nplanning_options: " + planning_options.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
