//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FetchVr
{
    [Serializable]
    public class ExampleMessageMsg : Message
    {
        public const string k_RosMessageName = "fetch_vr/ExampleMessage";
        public override string RosMessageName => k_RosMessageName;

        public string first_name;
        public string last_name;

        public ExampleMessageMsg()
        {
            this.first_name = "";
            this.last_name = "";
        }

        public ExampleMessageMsg(string first_name, string last_name)
        {
            this.first_name = first_name;
            this.last_name = last_name;
        }

        public static ExampleMessageMsg Deserialize(MessageDeserializer deserializer) => new ExampleMessageMsg(deserializer);

        private ExampleMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.first_name);
            deserializer.Read(out this.last_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.first_name);
            serializer.Write(this.last_name);
        }

        public override string ToString()
        {
            return "ExampleMessageMsg: " +
            "\nfirst_name: " + first_name.ToString() +
            "\nlast_name: " + last_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
