add_newline = false

format = """
[ROS](bold red) in \
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmake\
$conda\
$crystal\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$package\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$zig\
$cmd_duration\
$line_break\
$character"""

[character]
error_symbol = '[\$](bold red)'
success_symbol = '[\$](bold green)'

[cmake]
symbol = 'cmake '

[cmd_duration]
style = 'yellow'

[conda]
ignore_base = false
symbol = 'conda '

[crystal]
symbol = 'crystal '

[dart]
symbol = 'dart '

[directory]
read_only = '*'
read_only_style = 'bold red'
style = 'bold cyan'
truncation_length = 3
truncation_symbol = '...'

[dotnet]
format = 'via [$symbol$version( \($tfm\))]($style) '
symbol = 'dotnet '

[elixir]
symbol = 'elixir '

[elm]
symbol = 'elm '

[erlang]
symbol = 'erlang '

[git_branch]
style = 'bold purple'
symbol = ''

[git_commit]
commit_hash_length = 4
format = '[\(($tag, )$hash\)]($style) '
style = 'bold green'
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[\($state ($progress_current of $progress_total)\)]($style) '

[golang]
symbol = 'go '

[java]
symbol = 'java '

[julia]
symbol = 'julia '

[nim]
symbol = 'nim '

[nodejs]
symbol = 'node '

[ocaml]
symbol = 'ocaml '

[package]
style = 'bold yellow'
symbol = ''

[perl]
symbol = 'perl '

[php]
symbol = 'php '

[purescript]
symbol = 'purescript '

[python]
symbol = 'python '

[ruby]
symbol = 'ruby '

[rust]
symbol = 'rust '

[swift]
symbol = 'swift '

[zig]
symbol = 'zig '
